accounts/models.py
from django.db import models

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from accounts.forms import SignUpForm,AuthenticationForm
from django.contrib.auth import login,authenticate
from django.contrib import auth

def home(request):
	return render(request,'home.html')

def signup(request):
    form = SignUpForm(request.POST)
    if form.is_valid():	
        user = form.save()
        user.refresh_from_db()
        # user.profile.first_name = form.cleaned_data.get('first_name')
        # user.profile.last_name = form.cleaned_data.get('last_name')
        # user.profile.email = form.cleaned_data.get('email')
        # user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(request.POST)
		
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user:
			if user.is_active:
				login(request,user)
				
				return redirect('/visitor_app/visit')
			else:
				return HttpResponse("Your Account is Disabled")
		else:
			print ("Invalid login details: {0},{1}".format(username,password))
			return HttpResponse("Invalid login details supplied")
	else:
		form = AuthenticationForm()
	return render(request,'login.html',{'form':form})

def logout(request):
    auth.logout(request)
    return render(request,'logout.html')

accounts/templates/form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
  	<div class="form-control">
    {{ field | add_class:'input-class'}}
	</div>
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}  <!-- new code here -->
      </small>
    {% endif %}
  </div>
{% endfor %}

accounts/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Home</h1>
<div class="row">
	
    <div class="col-md-4">
        <div class="card mb-2">
            <div class="card-body">
                <a href="{% url 'login' %}"
                   class="btn btn-success" style="width: 310px;">
                    Login
                </a>
                <br/><br/>
                <a href="{% url 'signup' %}"
                   class="btn btn-primary" style="width: 310px;">
                    SignUp
                </a>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="logo mb-3">
             <div class="col-md-12 text-center">
              <h1>Login</h1>
             </div>
          </div>
    <form method="post">
  {% csrf_token %}
<div class="row">
  
    <div class="col-md-5 mx-auto">
        <div class="card mb-2"  style="border-radius: 32px !important;">
            <div class="card-body">
              <table>
                <tbody>
                  <tr>
                    <th><label style="margin-bottom: 2.5rem !important;" for="id_username">Username:</label></th>
                    <td><input type="text" class="form-control" name="username" autofocus required id="id_username"><br/><br/>  </td></tr>
                  
                  <tr>
                    <th><label style="margin-bottom: 2.5rem !important;" for="id_password">Password:</label></th>
                    <td><input type="password" class="form-control" name="password" required id="id_password"><br/><input type="checkbox" onclick="myFunction()">Show Password<br/><br/>  </td>
                  <script type="text/javascript">
                    function myFunction() {
                      var x = document.getElementById("id_password");
                      if (x.type === "password") {
                        x.type = "text";
                      } else {
                        x.type = "password";
                      }
                    }
                  </script>
                  </tr>
                </tbody>
              </table>
                <div class="col-md-12 text-center ">
                    <button type="submit" class=" btn btn-block mybtn btn-success tx-tfm">Login</button>
                </div>
            </div>
            <div class="col-md-12 text-center ">
              <a href="{% url 'password_reset'%}">Reset Password</a>
            </div>
            <div class="col-md-12 text-center ">
              Don't Have an Account ? <a href="{% url 'signup'%}">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
</form>
  </div>
{% endblock %}

accounts/templates/logout.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Logged Out</h1>
 <div class="content">
        <div class="section-inner clearfix">
 
        <p>You are logged out. <a href="{% url 'login' %}">Click here</a> to login again.</p>
 
        </div>
    </div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
 <div class="container">
    <div class="logo mb-3">
             <div class="col-md-12 text-center">
              <h1>Sign Up</h1>
             </div>
          </div>
    <form method="post">
  {% csrf_token %}
<div class="row">
  
    <div class="col-md-5 mx-auto">
        <div class="card mb-2" style="border-radius: 32px !important;" >
            <div class="card-body">
              <table>
                <tbody>
                  <tr>
                  	<th><label for="id_username" style="margin-bottom: 1.5rem !important;">Username:</label></th>
                  	<td>
                  		<input type="text" class="form-control" name="username" maxlength="30" autofocus required id="id_username"><br>
                  	</td>
                  </tr>
				<tr>
					<th><label for="id_email" style="margin-bottom: 1.5rem !important;">Email:</label></th>
					<td><input type="email" class="form-control" name="email" maxlength="200" required id="id_email"><br></td>
				</tr>
				<tr>
					<th><label for="id_password1" style="margin-bottom: 1.5rem !important;">Password:</label></th>
					<td><input type="password" class="form-control" name="password1" required id="id_password1"><br></td></tr>
				<tr>
					<th><label for="id_password2" style="margin-bottom: 1.5rem !important;">Password confirmation:</label></th>
					<td><input type="password" class="form-control" name="password2" required id="id_password2"><br></td></tr>
                </tbody>
              </table>
                <div class="col-md-12 text-center ">
                    <button type="submit" class=" btn btn-block mybtn btn-success tx-tfm">Create Account</button>
                </div>
            </div>
            <div class="col-md-12 text-center ">
              Already Have an Account ? <a href="{% url 'login'%}">Login</a>
            </div>
          </div>
        </div>
      </div>
</form>
  </div>
{% endblock %}